In [1]:
import pandas as pd

df = pd.read_csv("data/t20.csv")
df

,Unnamed: 0,Player,Span,Matches,Innings,Not Outs,Runs,Highest Score,Average,Balls Faced,Strike Rate,100,50,0,4s,6s,Unnamed: 15
0,0,V Kohli (INDIA),2010-2019,75,70,20,2633,94*,52.66,1907,138.07,0,24,2,247,71,NaN
1,1,RG Sharma (INDIA),2007-2019,104,96,14,2633,118,32.10,1905,138.21,4,19,6,234,120,NaN
2,2,MJ Guptill (NZ),2009-2019,83,80,7,2436,105,33.36,1810,134.58,2,15,2,215,113,NaN
3,3,Shoaib Malik (ICC/PAK),2006-2019,111,104,30,2263,75,30.58,1824,124.06,0,7,1,186,61,NaN
4,4,BB McCullum (NZ),2005-2015,71,70,10,2140,123,35.66,1571,136.21,2,13,3,199,91,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,45,SP Khakurel (NEPAL),2014-2015,8,8,0,112,56,14.00,139,80.57,0,1,0,10,1,NaN
496,46,JS Malhotra (USA),2019-2019,6,6,0,112,38,18.66,104,107.69,0,0,0,12,2,NaN
497,47,Mohammad Boota (UAE),2019-2019,16,12,4,112,20*,14.00,100,112.00,0,0,1,7,5,NaN
498,48,Mudassar Muhammad (GER),2019-2019,7,7,0,112,30,16.00,135,82.96,0,0,0,5,3,NaN
499,49,AP Devcich (NZ),2013-2014,4,4,0,111,59,27.75,79,140.50,0,1,0,17,2,NaN

In [2]:
df["not_drop"] = df["Player"].apply(lambda x: "(IND" in x)
df

,Unnamed: 0,Player,Span,Matches,Innings,Not Outs,Runs,Highest Score,Average,Balls Faced,Strike Rate,100,50,0,4s,6s,Unnamed: 15,not_drop
0,0,V Kohli (INDIA),2010-2019,75,70,20,2633,94*,52.66,1907,138.07,0,24,2,247,71,NaN,True
1,1,RG Sharma (INDIA),2007-2019,104,96,14,2633,118,32.10,1905,138.21,4,19,6,234,120,NaN,True
2,2,MJ Guptill (NZ),2009-2019,83,80,7,2436,105,33.36,1810,134.58,2,15,2,215,113,NaN,False
3,3,Shoaib Malik (ICC/PAK),2006-2019,111,104,30,2263,75,30.58,1824,124.06,0,7,1,186,61,NaN,False
4,4,BB McCullum (NZ),2005-2015,71,70,10,2140,123,35.66,1571,136.21,2,13,3,199,91,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,45,SP Khakurel (NEPAL),2014-2015,8,8,0,112,56,14.00,139,80.57,0,1,0,10,1,NaN,False
496,46,JS Malhotra (USA),2019-2019,6,6,0,112,38,18.66,104,107.69,0,0,0,12,2,NaN,False
497,47,Mohammad Boota (UAE),2019-2019,16,12,4,112,20*,14.00,100,112.00,0,0,1,7,5,NaN,False
498,48,Mudassar Muhammad (GER),2019-2019,7,7,0,112,30,16.00,135,82.96,0,0,0,5,3,NaN,False
499,49,AP Devcich (NZ),2013-2014,4,4,0,111,59,27.75,79,140.50,0,1,0,17,2,NaN,False

In [3]:
df.drop(["Unnamed: 0", "Unnamed: 15"], axis=1, inplace=True)
df

,Player,Span,Matches,Innings,Not Outs,Runs,Highest Score,Average,Balls Faced,Strike Rate,100,50,0,4s,6s,not_drop
0,V Kohli (INDIA),2010-2019,75,70,20,2633,94*,52.66,1907,138.07,0,24,2,247,71,True
1,RG Sharma (INDIA),2007-2019,104,96,14,2633,118,32.10,1905,138.21,4,19,6,234,120,True
2,MJ Guptill (NZ),2009-2019,83,80,7,2436,105,33.36,1810,134.58,2,15,2,215,113,False
3,Shoaib Malik (ICC/PAK),2006-2019,111,104,30,2263,75,30.58,1824,124.06,0,7,1,186,61,False
4,BB McCullum (NZ),2005-2015,71,70,10,2140,123,35.66,1571,136.21,2,13,3,199,91,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,SP Khakurel (NEPAL),2014-2015,8,8,0,112,56,14.00,139,80.57,0,1,0,10,1,False
496,JS Malhotra (USA),2019-2019,6,6,0,112,38,18.66,104,107.69,0,0,0,12,2,False
497,Mohammad Boota (UAE),2019-2019,16,12,4,112,20*,14.00,100,112.00,0,0,1,7,5,False
498,Mudassar Muhammad (GER),2019-2019,7,7,0,112,30,16.00,135,82.96,0,0,0,5,3,False
499,AP Devcich (NZ),2013-2014,4,4,0,111,59,27.75,79,140.50,0,1,0,17,2,False

In [4]:
df = df[df["not_drop"]==True]
df

,Player,Span,Matches,Innings,Not Outs,Runs,Highest Score,Average,Balls Faced,Strike Rate,100,50,0,4s,6s,not_drop
0,V Kohli (INDIA),2010-2019,75,70,20,2633,94*,52.66,1907,138.07,0,24,2,247,71,True
1,RG Sharma (INDIA),2007-2019,104,96,14,2633,118,32.10,1905,138.21,4,19,6,234,120,True
19,MS Dhoni (INDIA),2006-2019,98,85,42,1617,56,37.60,1282,126.13,0,2,1,116,52,True
22,SK Raina (INDIA),2006-2018,78,66,11,1605,101,29.18,1190,134.87,1,5,3,145,58,True
27,S Dhawan (INDIA),2011-2019,58,57,3,1504,92,27.85,1173,128.21,0,9,1,166,46,True
45,Yuvraj Singh (INDIA),2007-2017,58,51,9,1177,77*,28.02,863,136.38,0,8,1,77,74,True
51,KL Rahul (INDIA),2016-2019,34,31,5,1138,110*,43.76,777,146.46,2,8,1,102,50,True
66,G Gambhir (INDIA),2007-2012,37,36,2,932,75,27.41,783,119.02,0,7,2,109,10,True
108,MK Pandey (INDIA),2015-2019,32,27,12,587,79*,39.13,478,122.80,0,2,2,40,16,True
162,RR Pant (INDIA),2017-2019,26,24,4,409,65*,20.45,336,121.72,0,2,3,28,18,True
175,V Sehwag (INDIA),2006-2012,19,18,0,394,68,21.88,271,145.38,0,2,1,43,16,True
182,AM Rahane (INDIA),2011-2016,20,20,2,375,61,20.83,331,113.29,0,1,2,32,6,True
224,HH Pandya (INDIA),2016-2019,40,25,6,310,33*,16.31,210,147.61,0,0,2,18,19,True
267,RV Uthappa (INDIA),2007-2015,13,12,2,249,50,24.90,211,118.00,0,1,1,26,6,True
283,YK Pathan (INDIA),2007-2012,22,18,5,236,37*,18.15,161,146.58,0,0,3,11,17,True
297,SS Iyer (INDIA),2017-2019,14,13,3,226,62,22.60,178,126.96,0,1,1,18,9,True
372,IK Pathan (INDIA),2006-2012,24,14,7,172,33*,24.57,144,119.44,0,0,0,9,7,True
376,M Vijay (INDIA),2010-2015,9,9,0,169,48,18.77,154,109.74,0,0,1,13,8,True
382,RA Jadeja (INDIA),2009-2019,46,22,8,163,25,11.64,165,98.78,0,0,2,7,4,True
463,R Ashwin (INDIA),2010-2017,46,11,7,123,31*,30.75,115,106.95,0,0,0,14,1,True
467,KM Jadhav (INDIA),2015-2017,9,6,0,122,58,20.33,99,123.23,0,1,0,12,3,True
472,KH Pandya (INDIA),2018-2019,18,9,4,121,26*,24.20,92,131.52,0,0,0,8,6,True

In [5]:
df.drop(["not_drop"], axis=1, inplace=True)
df["Player"] = df["Player"].apply(lambda x: x.replace("(INDIA)", ""))
df

C:\Users\vasan\AppData\Local\Temp\ipykernel_17152\2011780209.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(["not_drop"], axis=1, inplace=True)
C:\Users\vasan\AppData\Local\Temp\ipykernel_17152\2011780209.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Player"] = df["Player"].apply(lambda x: x.replace("(INDIA)", ""))

,Player,Span,Matches,Innings,Not Outs,Runs,Highest Score,Average,Balls Faced,Strike Rate,100,50,0,4s,6s
0,V Kohli,2010-2019,75,70,20,2633,94*,52.66,1907,138.07,0,24,2,247,71
1,RG Sharma,2007-2019,104,96,14,2633,118,32.10,1905,138.21,4,19,6,234,120
19,MS Dhoni,2006-2019,98,85,42,1617,56,37.60,1282,126.13,0,2,1,116,52
22,SK Raina,2006-2018,78,66,11,1605,101,29.18,1190,134.87,1,5,3,145,58
27,S Dhawan,2011-2019,58,57,3,1504,92,27.85,1173,128.21,0,9,1,166,46
45,Yuvraj Singh,2007-2017,58,51,9,1177,77*,28.02,863,136.38,0,8,1,77,74
51,KL Rahul,2016-2019,34,31,5,1138,110*,43.76,777,146.46,2,8,1,102,50
66,G Gambhir,2007-2012,37,36,2,932,75,27.41,783,119.02,0,7,2,109,10
108,MK Pandey,2015-2019,32,27,12,587,79*,39.13,478,122.80,0,2,2,40,16
162,RR Pant,2017-2019,26,24,4,409,65*,20.45,336,121.72,0,2,3,28,18
175,V Sehwag,2006-2012,19,18,0,394,68,21.88,271,145.38,0,2,1,43,16
182,AM Rahane,2011-2016,20,20,2,375,61,20.83,331,113.29,0,1,2,32,6
224,HH Pandya,2016-2019,40,25,6,310,33*,16.31,210,147.61,0,0,2,18,19
267,RV Uthappa,2007-2015,13,12,2,249,50,24.90,211,118.00,0,1,1,26,6
283,YK Pathan,2007-2012,22,18,5,236,37*,18.15,161,146.58,0,0,3,11,17
297,SS Iyer,2017-2019,14,13,3,226,62,22.60,178,126.96,0,1,1,18,9
372,IK Pathan,2006-2012,24,14,7,172,33*,24.57,144,119.44,0,0,0,9,7
376,M Vijay,2010-2015,9,9,0,169,48,18.77,154,109.74,0,0,1,13,8
382,RA Jadeja,2009-2019,46,22,8,163,25,11.64,165,98.78,0,0,2,7,4
463,R Ashwin,2010-2017,46,11,7,123,31*,30.75,115,106.95,0,0,0,14,1
467,KM Jadhav,2015-2017,9,6,0,122,58,20.33,99,123.23,0,1,0,12,3
472,KH Pandya,2018-2019,18,9,4,121,26*,24.20,92,131.52,0,0,0,8,6

In [6]:
df.drop("Span", axis=1, inplace=True)
df

C:\Users\vasan\AppData\Local\Temp\ipykernel_17152\2208083445.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop("Span", axis=1, inplace=True)

,Player,Matches,Innings,Not Outs,Runs,Highest Score,Average,Balls Faced,Strike Rate,100,50,0,4s,6s
0,V Kohli,75,70,20,2633,94*,52.66,1907,138.07,0,24,2,247,71
1,RG Sharma,104,96,14,2633,118,32.10,1905,138.21,4,19,6,234,120
19,MS Dhoni,98,85,42,1617,56,37.60,1282,126.13,0,2,1,116,52
22,SK Raina,78,66,11,1605,101,29.18,1190,134.87,1,5,3,145,58
27,S Dhawan,58,57,3,1504,92,27.85,1173,128.21,0,9,1,166,46
45,Yuvraj Singh,58,51,9,1177,77*,28.02,863,136.38,0,8,1,77,74
51,KL Rahul,34,31,5,1138,110*,43.76,777,146.46,2,8,1,102,50
66,G Gambhir,37,36,2,932,75,27.41,783,119.02,0,7,2,109,10
108,MK Pandey,32,27,12,587,79*,39.13,478,122.80,0,2,2,40,16
162,RR Pant,26,24,4,409,65*,20.45,336,121.72,0,2,3,28,18
175,V Sehwag,19,18,0,394,68,21.88,271,145.38,0,2,1,43,16
182,AM Rahane,20,20,2,375,61,20.83,331,113.29,0,1,2,32,6
224,HH Pandya,40,25,6,310,33*,16.31,210,147.61,0,0,2,18,19
267,RV Uthappa,13,12,2,249,50,24.90,211,118.00,0,1,1,26,6
283,YK Pathan,22,18,5,236,37*,18.15,161,146.58,0,0,3,11,17
297,SS Iyer,14,13,3,226,62,22.60,178,126.96,0,1,1,18,9
372,IK Pathan,24,14,7,172,33*,24.57,144,119.44,0,0,0,9,7
376,M Vijay,9,9,0,169,48,18.77,154,109.74,0,0,1,13,8
382,RA Jadeja,46,22,8,163,25,11.64,165,98.78,0,0,2,7,4
463,R Ashwin,46,11,7,123,31*,30.75,115,106.95,0,0,0,14,1
467,KM Jadhav,9,6,0,122,58,20.33,99,123.23,0,1,0,12,3
472,KH Pandya,18,9,4,121,26*,24.20,92,131.52,0,0,0,8,6

In [7]:
df.to_csv("data/ind.csv", index=False)